<?php

namespace MHErrorHandler;

class MHException extends \Exception
    {
        private $time;
        public function __construct($message ="Undefined Exception", $code = 0, \Throwable $previous = null)
        {
            parent($message, $code, $previous);
            $this->time = date("Y-m-d H:i:s", time());
        }
        public function __toString(): string
        {
            return parent::__toString(); // TODO: Change the autogenerated stub
        }
}