.TH "Framework/database Directory Reference" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Framework/database Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCategoryAccess\&.php\fP"
.br
.ti -1c
.RI "file \fBCommentAccess\&.php\fP"
.br
.ti -1c
.RI "file \fBGeneralAccess\&.php\fP"
.br
.ti -1c
.RI "file \fBSPDO\&.php\fP"
.br
.ti -1c
.RI "file \fBTicketAccess\&.php\fP"
.br
.ti -1c
.RI "file \fBUserAccess\&.php\fP"
.br
.in -1c
