.TH "controls Directory Reference" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controls Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBpagePresenters\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBController\&.php\fP"
.br
.ti -1c
.RI "file \fBPresenter\&.php\fP"
.br
.in -1c
