.TH "gui Directory Reference" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBLayout\&.php\fP"
.br
.ti -1c
.RI "file \fBView\&.php\fP"
.br
.ti -1c
.RI "file \fBViewCategories\&.php\fP"
.br
.ti -1c
.RI "file \fBViewCreateCategory\&.php\fP"
.br
.ti -1c
.RI "file \fBViewCreatePosts\&.php\fP"
.br
.ti -1c
.RI "file \fBViewEditTicket\&.php\fP"
.br
.ti -1c
.RI "file \fBViewError\&.php\fP"
.br
.ti -1c
.RI "file \fBViewHomepage\&.php\fP"
.br
.ti -1c
.RI "file \fBViewLogin\&.php\fP"
.br
.ti -1c
.RI "file \fBViewPosts\&.php\fP"
.br
.ti -1c
.RI "file \fBViewRegister\&.php\fP"
.br
.ti -1c
.RI "file \fBViewUserEdit\&.php\fP"
.br
.ti -1c
.RI "file \fBViewUsers\&.php\fP"
.br
.in -1c
