.TH "services Directory Reference" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
services Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCategoriesService\&.php\fP"
.br
.ti -1c
.RI "file \fBCategoryInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBCommentInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBCommentsService\&.php\fP"
.br
.ti -1c
.RI "file \fBOutputData\&.php\fP"
.br
.ti -1c
.RI "file \fBTicketInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBTicketsService\&.php\fP"
.br
.ti -1c
.RI "file \fBUserInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBUsersService\&.php\fP"
.br
.in -1c
