.TH "controls/pagePresenters Directory Reference" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controls/pagePresenters Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcategories\&.php\fP"
.br
.ti -1c
.RI "file \fBcategory\&.php\fP"
.br
.ti -1c
.RI "file \fBcreateTicket\&.php\fP"
.br
.ti -1c
.RI "file \fBeditTicket\&.php\fP"
.br
.ti -1c
.RI "file \fBhomepage\&.php\fP"
.br
.ti -1c
.RI "file \fBpost\&.php\fP"
.br
.ti -1c
.RI "file \fBposts\&.php\fP"
.br
.ti -1c
.RI "file \fBuser\&.php\fP"
.br
.ti -1c
.RI "file \fBuserEdit\&.php\fP"
.br
.ti -1c
.RI "file \fBusers\&.php\fP"
.br
.in -1c
