.TH "Framework/database/CategoryAccess.php" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Framework/database/CategoryAccess.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCategoryAccess\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBdatabase\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
