.TH "controls/Controller.php" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controls/Controller.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBController\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcontrols\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
