.TH "Presenter" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Presenter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($outputData)"
.br
.ti -1c
.RI "\fBshow\fP ($presenterName)"
.br
.ti -1c
.RI "\fBshowCategory\fP ($category)"
.br
.ti -1c
.RI "\fBshowUser\fP ($user)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBPresenter\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $outputData)"

.PP
Definition at line \fB12\fP of file \fBPresenter\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "show ( $presenterName)"

.PP
\fBParameters\fP
.RS 4
\fI$presenterName\fP 
.RE
.PP
\fBReturns\fP
.RS 4
false|string 
.RE
.PP

.PP
Definition at line \fB21\fP of file \fBPresenter\&.php\fP\&.
.SS "showCategory ( $category)"

.PP
\fBParameters\fP
.RS 4
\fI$category\fP 
.RE
.PP
\fBReturns\fP
.RS 4
false|string 
.RE
.PP

.PP
Definition at line \fB34\fP of file \fBPresenter\&.php\fP\&.
.SS "showUser ( $user)"

.PP
\fBParameters\fP
.RS 4
\fI$user\fP 
.RE
.PP
\fBReturns\fP
.RS 4
false|string 
.RE
.PP

.PP
Definition at line \fB47\fP of file \fBPresenter\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
