.TH "database" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
database
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCategoryAccess\fP"
.br
.ti -1c
.RI "class \fBCommentAccess\fP"
.br
.ti -1c
.RI "class \fBGeneralAccess\fP"
.br
.ti -1c
.RI "class \fBSPDO\fP"
.br
.ti -1c
.RI "class \fBTicketAccess\fP"
.br
.ti -1c
.RI "class \fBUserAccess\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
