.TH "SPDO" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPDO
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBprepare\fP ($query)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetInstance\fP (string $serverName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBSPDO\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static getInstance (string $serverName)\fC [static]\fP"

.PP
\fBParameters\fP
.RS 4
\fI$serverName\fP 
.RE
.PP
\fBReturns\fP
.RS 4
SPDO 
.RE
.PP

.PP
Definition at line \fB44\fP of file \fBSPDO\&.php\fP\&.
.SS "prepare ( $query)"

.PP
\fBParameters\fP
.RS 4
\fI$query\fP 
.RE
.PP
\fBReturns\fP
.RS 4
false|\\PDOStatement 
.RE
.PP

.PP
Definition at line \fB56\fP of file \fBSPDO\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
