.TH "controls/pagePresenters/editTicket.php" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controls/pagePresenters/editTicket.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$post\fP = $data"
.br
.ti -1c
.RI "\fB$id\fP = $post\->getTicket()\->getTicket_ID()"
.br
.ti -1c
.RI "\fB$title\fP = $post\->getTicket()\->getTitle()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$id = $post\->getTicket()\->getTicket_ID()"

.PP
Definition at line \fB2\fP of file \fBeditTicket\&.php\fP\&.
.SS "$post = $data"

.PP
Definition at line \fB1\fP of file \fBeditTicket\&.php\fP\&.
.SS "$title = $post\->getTicket()\->getTitle()"

.PP
Definition at line \fB3\fP of file \fBeditTicket\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
