.TH "Post" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Post
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($ticket, $categories, $comments, $user)"
.br
.ti -1c
.RI "\fBgetTicket\fP ()"
.br
.ti -1c
.RI "\fBgetCategories\fP ()"
.br
.ti -1c
.RI "\fBgetComments\fP ()"
.br
.ti -1c
.RI "\fBgetUser\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBPost\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $ticket,  $categories,  $comments,  $user)"

.PP
\fBParameters\fP
.RS 4
\fI$ticket\fP 
.br
\fI$categories\fP 
.br
\fI$comments\fP 
.br
\fI$user\fP 
.RE
.PP

.PP
Definition at line \fB30\fP of file \fBPost\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getCategories ()"

.PP
\fBReturns\fP
.RS 4
Category[] 
.RE
.PP

.PP
Definition at line \fB49\fP of file \fBPost\&.php\fP\&.
.SS "getComments ()"

.PP
\fBReturns\fP
.RS 4
Comment[] 
.RE
.PP

.PP
Definition at line \fB57\fP of file \fBPost\&.php\fP\&.
.SS "getTicket ()"

.PP
\fBReturns\fP
.RS 4
Ticket 
.RE
.PP

.PP
Definition at line \fB41\fP of file \fBPost\&.php\fP\&.
.SS "getUser ()"

.PP
\fBReturns\fP
.RS 4
User 
.RE
.PP

.PP
Definition at line \fB65\fP of file \fBPost\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
