.TH "entities" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
entities
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCategory\fP"
.br
.ti -1c
.RI "class \fBComment\fP"
.br
.ti -1c
.RI "class \fBEntity\fP"
.br
.ti -1c
.RI "class \fBPost\fP"
.br
.ti -1c
.RI "class \fBTicket\fP"
.br
.ti -1c
.RI "class \fBUser\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
