.TH "Category" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Category
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEntity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetCategory_ID\fP ()"
.br
.ti -1c
.RI "\fBsetCategory_ID\fP ($category_ID)"
.br
.ti -1c
.RI "\fBgetLabel\fP ()"
.br
.ti -1c
.RI "\fBsetLabel\fP ($label)"
.br
.ti -1c
.RI "\fBgetDescription\fP ()"
.br
.ti -1c
.RI "\fBsetDescription\fP ($description)"
.br
.in -1c

Public Member Functions inherited from \fBEntity\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP (array $data)"
.br
.ti -1c
.RI "\fBhydrate\fP ($data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBCategory\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getCategory_ID ()"

.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line \fB25\fP of file \fBCategory\&.php\fP\&.
.SS "getDescription ()"

.PP
\fBReturns\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line \fB64\fP of file \fBCategory\&.php\fP\&.
.SS "getLabel ()"

.PP
\fBReturns\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBCategory\&.php\fP\&.
.SS "setCategory_ID ( $category_ID)"

.PP
\fBParameters\fP
.RS 4
\fI$category_ID\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB34\fP of file \fBCategory\&.php\fP\&.
.SS "setDescription ( $description)"

.PP
\fBParameters\fP
.RS 4
\fI$description\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB73\fP of file \fBCategory\&.php\fP\&.
.SS "setLabel ( $label)"

.PP
\fBParameters\fP
.RS 4
\fI$label\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB54\fP of file \fBCategory\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
