.TH "Ticket" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ticket
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEntity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetTicket_ID\fP ()"
.br
.ti -1c
.RI "\fBsetTicket_ID\fP ($ticket_ID)"
.br
.ti -1c
.RI "\fBgetTitle\fP ()"
.br
.ti -1c
.RI "\fBsetTitle\fP ($title)"
.br
.ti -1c
.RI "\fBgetMessage\fP ()"
.br
.ti -1c
.RI "\fBsetMessage\fP ($message)"
.br
.ti -1c
.RI "\fBgetDate\fP ()"
.br
.ti -1c
.RI "\fBsetDate\fP ($date)"
.br
.ti -1c
.RI "\fBgetAuthor\fP ()"
.br
.ti -1c
.RI "\fBsetAuthor\fP ($author)"
.br
.in -1c

Public Member Functions inherited from \fBEntity\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP (array $data)"
.br
.ti -1c
.RI "\fBhydrate\fP ($data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBTicket\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getAuthor ()"

.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line \fB108\fP of file \fBTicket\&.php\fP\&.
.SS "getDate ()"

.PP
\fBReturns\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line \fB91\fP of file \fBTicket\&.php\fP\&.
.SS "getMessage ()"

.PP
\fBReturns\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line \fB72\fP of file \fBTicket\&.php\fP\&.
.SS "getTicket_ID ()"

.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line \fB33\fP of file \fBTicket\&.php\fP\&.
.SS "getTitle ()"

.PP
\fBReturns\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line \fB53\fP of file \fBTicket\&.php\fP\&.
.SS "setAuthor ( $author)"

.PP
\fBParameters\fP
.RS 4
\fI$author\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB117\fP of file \fBTicket\&.php\fP\&.
.SS "setDate ( $date)"

.PP
\fBParameters\fP
.RS 4
\fI$date\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB100\fP of file \fBTicket\&.php\fP\&.
.SS "setMessage ( $message)"

.PP
\fBParameters\fP
.RS 4
\fI$message\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB81\fP of file \fBTicket\&.php\fP\&.
.SS "setTicket_ID ( $ticket_ID)"

.PP
\fBParameters\fP
.RS 4
\fI$ticket_ID\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB42\fP of file \fBTicket\&.php\fP\&.
.SS "setTitle ( $title)"

.PP
\fBParameters\fP
.RS 4
\fI$title\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB62\fP of file \fBTicket\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
