.TH "User" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
User
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEntity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetUser_ID\fP ()"
.br
.ti -1c
.RI "\fBsetUser_ID\fP ($user_ID)"
.br
.ti -1c
.RI "\fBgetPassword\fP ()"
.br
.ti -1c
.RI "\fBsetPassword\fP ($password)"
.br
.ti -1c
.RI "\fBgetUsername\fP ()"
.br
.ti -1c
.RI "\fBsetUsername\fP ($username)"
.br
.ti -1c
.RI "\fBgetFirst_connexion\fP ()"
.br
.ti -1c
.RI "\fBsetFirst_connexion\fP ($first_connexion)"
.br
.ti -1c
.RI "\fBgetLast_connexion\fP ()"
.br
.ti -1c
.RI "\fBsetLast_connexion\fP ($last_connexion)"
.br
.ti -1c
.RI "\fBgetLevel\fP ()"
.br
.ti -1c
.RI "\fBsetLevel\fP ($level)"
.br
.ti -1c
.RI "\fBgetOnline\fP ()"
.br
.ti -1c
.RI "\fBsetOnline\fP ($online)"
.br
.in -1c

Public Member Functions inherited from \fBEntity\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP (array $data)"
.br
.ti -1c
.RI "\fBhydrate\fP ($data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBUser\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getFirst_connexion ()"

.PP
\fBReturns\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line \fB99\fP of file \fBUser\&.php\fP\&.
.SS "getLast_connexion ()"

.PP
\fBReturns\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line \fB116\fP of file \fBUser\&.php\fP\&.
.SS "getLevel ()"

.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line \fB133\fP of file \fBUser\&.php\fP\&.
.SS "getOnline ()"

.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line \fB152\fP of file \fBUser\&.php\fP\&.
.SS "getPassword ()"

.PP
\fBReturns\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line \fB61\fP of file \fBUser\&.php\fP\&.
.SS "getUser_ID ()"

.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line \fB41\fP of file \fBUser\&.php\fP\&.
.SS "getUsername ()"

.PP
\fBReturns\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line \fB80\fP of file \fBUser\&.php\fP\&.
.SS "setFirst_connexion ( $first_connexion)"

.PP
\fBParameters\fP
.RS 4
\fI$first_connexion\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB108\fP of file \fBUser\&.php\fP\&.
.SS "setLast_connexion ( $last_connexion)"

.PP
\fBParameters\fP
.RS 4
\fI$last_connexion\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB125\fP of file \fBUser\&.php\fP\&.
.SS "setLevel ( $level)"

.PP
\fBParameters\fP
.RS 4
\fI$level\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB142\fP of file \fBUser\&.php\fP\&.
.SS "setOnline ( $online)"

.PP
\fBParameters\fP
.RS 4
\fI$online\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB160\fP of file \fBUser\&.php\fP\&.
.SS "setPassword ( $password)"

.PP
\fBParameters\fP
.RS 4
\fI$password\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB70\fP of file \fBUser\&.php\fP\&.
.SS "setUser_ID ( $user_ID)"

.PP
\fBParameters\fP
.RS 4
\fI$user_ID\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB50\fP of file \fBUser\&.php\fP\&.
.SS "setUsername ( $username)"

.PP
\fBParameters\fP
.RS 4
\fI$username\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB89\fP of file \fBUser\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
