.TH "Comment" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Comment
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEntity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUsername\fP ($author_username)"
.br
.ti -1c
.RI "\fBgetComment_ID\fP ()"
.br
.ti -1c
.RI "\fBsetComment_ID\fP ($comment_ID)"
.br
.ti -1c
.RI "\fBgetText\fP ()"
.br
.ti -1c
.RI "\fBsetText\fP ($text)"
.br
.ti -1c
.RI "\fBgetDate\fP ()"
.br
.ti -1c
.RI "\fBsetDate\fP ($date)"
.br
.ti -1c
.RI "\fBgetAuthor\fP ()"
.br
.ti -1c
.RI "\fBsetAuthor\fP ($author)"
.br
.ti -1c
.RI "\fBgetAuthor_username\fP ()"
.br
.ti -1c
.RI "\fBgetTicket\fP ()"
.br
.ti -1c
.RI "\fBsetTicket\fP ($ticket)"
.br
.in -1c

Public Member Functions inherited from \fBEntity\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP (array $data)"
.br
.ti -1c
.RI "\fBhydrate\fP ($data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBComment\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getAuthor ()"

.PP
\fBReturns\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line \fB104\fP of file \fBComment\&.php\fP\&.
.SS "getAuthor_username ()"

.PP
\fBReturns\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line \fB124\fP of file \fBComment\&.php\fP\&.
.SS "getComment_ID ()"

.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line \fB48\fP of file \fBComment\&.php\fP\&.
.SS "getDate ()"

.PP
\fBReturns\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line \fB87\fP of file \fBComment\&.php\fP\&.
.SS "getText ()"

.PP
\fBReturns\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line \fB68\fP of file \fBComment\&.php\fP\&.
.SS "getTicket ()"

.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line \fB132\fP of file \fBComment\&.php\fP\&.
.SS "setAuthor ( $author)"

.PP
\fBParameters\fP
.RS 4
\fI$author\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB113\fP of file \fBComment\&.php\fP\&.
.SS "setComment_ID ( $comment_ID)"

.PP
\fBParameters\fP
.RS 4
\fI$comment_ID\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB57\fP of file \fBComment\&.php\fP\&.
.SS "setDate ( $date)"

.PP
\fBParameters\fP
.RS 4
\fI$date\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB96\fP of file \fBComment\&.php\fP\&.
.SS "setText ( $text)"

.PP
\fBParameters\fP
.RS 4
\fI$text\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB77\fP of file \fBComment\&.php\fP\&.
.SS "setTicket ( $ticket)"

.PP
\fBParameters\fP
.RS 4
\fI$ticket\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB141\fP of file \fBComment\&.php\fP\&.
.SS "setUsername ( $author_username)"

.PP
\fBParameters\fP
.RS 4
\fI$author_username\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line \fB38\fP of file \fBComment\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
