.TH "ViewPosts" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewPosts
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBView\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($layout, $presenter)"
.br
.in -1c

Public Member Functions inherited from \fBView\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP ($layout)"
.br
.ti -1c
.RI "\fBdisplay\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBView\fP
.in +1c
.ti -1c
.RI "\fB$title\fP = ''"
.br
.ti -1c
.RI "\fB$content\fP = ''"
.br
.ti -1c
.RI "\fB$username\fP = ''"
.br
.ti -1c
.RI "\fB$searchBar\fP = null"
.br
.ti -1c
.RI "\fB$layout\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBViewPosts\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $layout,  $presenter)"

.PP
Definition at line \fB7\fP of file \fBViewPosts\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
