.TH "UserInterface" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserInterface
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBUserAccess\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexistsUsername\fP ($username)"
.br
.ti -1c
.RI "\fBexistsUser\fP ($user_ID)"
.br
.ti -1c
.RI "\fBgetUserByUsername\fP ($username)"
.br
.ti -1c
.RI "\fBisUser\fP ($username, $password)"
.br
.ti -1c
.RI "\fBregister\fP ($username, $password, $date)"
.br
.ti -1c
.RI "\fBupdateUser\fP ($username, $password, $user_ID)"
.br
.ti -1c
.RI "\fBupdateLastConnexion\fP ($user_ID)"
.br
.ti -1c
.RI "\fBgetUserById\fP ($id)"
.br
.ti -1c
.RI "\fBgetUsersID\fP ()"
.br
.ti -1c
.RI "\fBget10LastConnectedUsersID\fP ()"
.br
.ti -1c
.RI "\fBsetOnline\fP ($user_ID, $online)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBUserInterface\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "existsUser ( $user_ID)"

.PP
Implemented in \fBUserAccess\fP\&.
.SS "existsUsername ( $username)"

.PP
Implemented in \fBUserAccess\fP\&.
.SS "get10LastConnectedUsersID ()"

.PP
Implemented in \fBUserAccess\fP\&.
.SS "getUserById ( $id)"

.PP
Implemented in \fBUserAccess\fP\&.
.SS "getUserByUsername ( $username)"

.PP
Implemented in \fBUserAccess\fP\&.
.SS "getUsersID ()"

.PP
Implemented in \fBUserAccess\fP\&.
.SS "isUser ( $username,  $password)"

.PP
Implemented in \fBUserAccess\fP\&.
.SS "register ( $username,  $password,  $date)"

.PP
Implemented in \fBUserAccess\fP\&.
.SS "setOnline ( $user_ID,  $online)"

.PP
Implemented in \fBUserAccess\fP\&.
.SS "updateLastConnexion ( $user_ID)"

.PP
Implemented in \fBUserAccess\fP\&.
.SS "updateUser ( $username,  $password,  $user_ID)"

.PP
Implemented in \fBUserAccess\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
