.TH "CommentInterface" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommentInterface
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCommentAccess\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcreateComment\fP ($text, $date, $user_ID, $ticket_ID)"
.br
.ti -1c
.RI "\fBisCommentOwner\fP ($commentID, $user_ID)"
.br
.ti -1c
.RI "\fBdeleteComment\fP ($commentID)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBCommentInterface\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "createComment ( $text,  $date,  $user_ID,  $ticket_ID)"

.PP
Implemented in \fBCommentAccess\fP\&.
.SS "deleteComment ( $commentID)"

.PP
Implemented in \fBCommentAccess\fP\&.
.SS "isCommentOwner ( $commentID,  $user_ID)"

.PP
Implemented in \fBCommentAccess\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
