.TH "OutputData" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OutputData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__destruct\fP ()"
.br
.ti -1c
.RI "\fBgetOutputData\fP ()"
.br
.ti -1c
.RI "\fBsetOutputData\fP ($data)"
.br
.ti -1c
.RI "\fBaddOutputData\fP ($data)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$outputData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBOutputData\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__destruct ()"

.PP
Definition at line \fB9\fP of file \fBOutputData\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "addOutputData ( $data)"

.PP
Definition at line \fB24\fP of file \fBOutputData\&.php\fP\&.
.SS "getOutputData ()"

.PP
Definition at line \fB14\fP of file \fBOutputData\&.php\fP\&.
.SS "setOutputData ( $data)"

.PP
Definition at line \fB19\fP of file \fBOutputData\&.php\fP\&.
.SH "Field Documentation"
.PP 
.SS "$outputData\fC [protected]\fP"

.PP
Definition at line \fB7\fP of file \fBOutputData\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
