.TH "CategoryInterface" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CategoryInterface
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCategoryAccess\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexistsCategory\fP ($CategoryID)"
.br
.ti -1c
.RI "\fBgetCategoriesID\fP ()"
.br
.ti -1c
.RI "\fBgetCategoryById\fP ($id)"
.br
.ti -1c
.RI "\fBgetCategoryIdByLabel\fP ($label)"
.br
.ti -1c
.RI "\fBget5LastCategories\fP ()"
.br
.ti -1c
.RI "\fBcreateCategory\fP ($label, $description)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBCategoryInterface\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "createCategory ( $label,  $description)"

.PP
Implemented in \fBCategoryAccess\fP\&.
.SS "existsCategory ( $CategoryID)"

.PP
Implemented in \fBCategoryAccess\fP\&.
.SS "get5LastCategories ()"

.PP
Implemented in \fBCategoryAccess\fP\&.
.SS "getCategoriesID ()"

.PP
Implemented in \fBCategoryAccess\fP\&.
.SS "getCategoryById ( $id)"

.PP
Implemented in \fBCategoryAccess\fP\&.
.SS "getCategoryIdByLabel ( $label)"

.PP
Implemented in \fBCategoryAccess\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
