.TH "services" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
services
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCategoriesService\fP"
.br
.ti -1c
.RI "interface \fBCategoryInterface\fP"
.br
.ti -1c
.RI "interface \fBCommentInterface\fP"
.br
.ti -1c
.RI "class \fBCommentsService\fP"
.br
.ti -1c
.RI "class \fBOutputData\fP"
.br
.ti -1c
.RI "interface \fBTicketInterface\fP"
.br
.ti -1c
.RI "class \fBTicketsService\fP"
.br
.ti -1c
.RI "interface \fBUserInterface\fP"
.br
.ti -1c
.RI "class \fBUsersService\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
