.TH "UsersService" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UsersService
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($outputData)"
.br
.ti -1c
.RI "\fBexistsUsername\fP ($dataccess, $username)"
.br
.ti -1c
.RI "\fBexistsUser\fP ($dataccess, $user_ID)"
.br
.ti -1c
.RI "\fBauthenticate\fP ($username, $password, $dataccess)"
.br
.ti -1c
.RI "\fBregister\fP ($username, $password, $dataccess)"
.br
.ti -1c
.RI "\fBupdateUser\fP ($username, $password, $dataccess)"
.br
.ti -1c
.RI "\fBgetUserByUsername\fP ($dataccess, $username)"
.br
.ti -1c
.RI "\fBupdateLastConnexion\fP ($dataccess, $user_ID)"
.br
.ti -1c
.RI "\fBgetUsers\fP ($dataccess)"
.br
.ti -1c
.RI "\fBgetUserById\fP ($dataccess, $id)"
.br
.ti -1c
.RI "\fBsetOnline\fP ($dataccess, $user_ID, $online)"
.br
.ti -1c
.RI "\fBadd10LastConnectedUsers\fP ($userAccessLector)"
.br
.ti -1c
.RI "\fBsetUserById\fP ($dataccess, $id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBUsersService\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $outputData)"

.PP
Definition at line \fB9\fP of file \fBUsersService\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "add10LastConnectedUsers ( $userAccessLector)"

.PP
Definition at line \fB68\fP of file \fBUsersService\&.php\fP\&.
.SS "authenticate ( $username,  $password,  $dataccess)"

.PP
Definition at line \fB24\fP of file \fBUsersService\&.php\fP\&.
.SS "existsUser ( $dataccess,  $user_ID)"

.PP
Definition at line \fB19\fP of file \fBUsersService\&.php\fP\&.
.SS "existsUsername ( $dataccess,  $username)"

.PP
Definition at line \fB14\fP of file \fBUsersService\&.php\fP\&.
.SS "getUserById ( $dataccess,  $id)"

.PP
Definition at line \fB59\fP of file \fBUsersService\&.php\fP\&.
.SS "getUserByUsername ( $dataccess,  $username)"

.PP
Definition at line \fB40\fP of file \fBUsersService\&.php\fP\&.
.SS "getUsers ( $dataccess)"

.PP
Definition at line \fB50\fP of file \fBUsersService\&.php\fP\&.
.SS "register ( $username,  $password,  $dataccess)"

.PP
Definition at line \fB30\fP of file \fBUsersService\&.php\fP\&.
.SS "setOnline ( $dataccess,  $user_ID,  $online)"

.PP
Definition at line \fB63\fP of file \fBUsersService\&.php\fP\&.
.SS "setUserById ( $dataccess,  $id)"

.PP
Definition at line \fB77\fP of file \fBUsersService\&.php\fP\&.
.SS "updateLastConnexion ( $dataccess,  $user_ID)"

.PP
Definition at line \fB45\fP of file \fBUsersService\&.php\fP\&.
.SS "updateUser ( $username,  $password,  $dataccess)"

.PP
Definition at line \fB35\fP of file \fBUsersService\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
