.TH "CommentsService" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommentsService
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($outputData)"
.br
.ti -1c
.RI "\fBcreateComment\fP ($commentAccess, $text, $ticketID)"
.br
.ti -1c
.RI "\fBisCommentOwner\fP ($commentAccess, $commentID, $user_ID)"
.br
.ti -1c
.RI "\fBdeleteComment\fP ($commentAccess, $commentID)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBCommentsService\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $outputData)"

.PP
Definition at line \fB10\fP of file \fBCommentsService\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "createComment ( $commentAccess,  $text,  $ticketID)"

.PP
Definition at line \fB15\fP of file \fBCommentsService\&.php\fP\&.
.SS "deleteComment ( $commentAccess,  $commentID)"

.PP
Definition at line \fB25\fP of file \fBCommentsService\&.php\fP\&.
.SS "isCommentOwner ( $commentAccess,  $commentID,  $user_ID)"

.PP
Definition at line \fB20\fP of file \fBCommentsService\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
