.TH "CategoriesService" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CategoriesService
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($outputData)"
.br
.ti -1c
.RI "\fBexistsCategory\fP ($categoriesAccess, $CategoryID)"
.br
.ti -1c
.RI "\fBcreateCategory\fP ($categoriesAccess, $label, $description)"
.br
.ti -1c
.RI "\fBgetCategories\fP ($categoriesAccess)"
.br
.ti -1c
.RI "\fBgetCategoryById\fP ($categoriesAccess, $categoryId)"
.br
.ti -1c
.RI "\fBgetCategoryIdByLabel\fP ($categoriesAccess, $category)"
.br
.ti -1c
.RI "\fBadd5LastCategories\fP ($categoriesAccess)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBCategoriesService\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $outputData)"

.PP
Definition at line \fB9\fP of file \fBCategoriesService\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "add5LastCategories ( $categoriesAccess)"

.PP
Definition at line \fB42\fP of file \fBCategoriesService\&.php\fP\&.
.SS "createCategory ( $categoriesAccess,  $label,  $description)"

.PP
Definition at line \fB19\fP of file \fBCategoriesService\&.php\fP\&.
.SS "existsCategory ( $categoriesAccess,  $CategoryID)"

.PP
Definition at line \fB14\fP of file \fBCategoriesService\&.php\fP\&.
.SS "getCategories ( $categoriesAccess)"

.PP
Definition at line \fB24\fP of file \fBCategoriesService\&.php\fP\&.
.SS "getCategoryById ( $categoriesAccess,  $categoryId)"

.PP
Definition at line \fB33\fP of file \fBCategoriesService\&.php\fP\&.
.SS "getCategoryIdByLabel ( $categoriesAccess,  $category)"

.PP
Definition at line \fB38\fP of file \fBCategoriesService\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
