.TH "Framework/entities/Ticket.php" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Framework/entities/Ticket.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBTicket\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBentities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
