.TH "controls/pagePresenters/userEdit.php" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controls/pagePresenters/userEdit.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$user\fP = $data"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$user = $data"

.PP
Definition at line \fB1\fP of file \fBuserEdit\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
