.TH "gui/ViewEditTicket.php" 3 "MetaHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/ViewEditTicket.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBViewEditTicket\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaHub from the source code\&.
